fixtures:
  symlinks:
    selenium: "#{source_dir}"
  repositories:
    logrotate: "git://github.com/rodjek/puppet-logrotate"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    r9util: "git://github.com/kayakco/puppet-r9util"
    bluepill: "git://github.com/kayakco/puppet-bluepill"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile"
    epel: "git://github.com/stahnma/puppet-module-epel"
